demos3:
  s3:
    s3_endpoint: "https://play.min.io"
    s3_client: "Q3AM3UQ867SPQQA43P2F"
    s3_secret: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    s3_bucket: "yuriichv"
spring:
  kafka:
    # - kafka in linux.local:9092 :
    bootstrap-servers: linux.local:9092