version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
        #      - KAFKA_HEAP_OPTS="-Xmx512m -Xms256m"
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://linux.local:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka-rest:
      image: confluentinc/cp-kafka-rest
      hostname: kafka-rest
      depends_on:
        - kafka
      environment:
        KAFKA_REST_HOST_NAME: kafka-rest
        KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9093
  kafka-topics-ui:
      image: landoop/kafka-topics-ui
      container_name: kafka-topics-ui
      ports:
        - 8000:8000
      depends_on:
        - kafka-rest
      environment:
        KAFKA_REST_PROXY_URL: "http://linux.local:8082"
        PROXY: "true"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
